describe ('test' ,() => {
    it('newissue test' , () => {
        cy.visit('http://localhost:3100/')
        cy.get('.login').click()
        cy.get('#username').click()
        cy.get('#username').type('admin')
        cy.get('#password').click()
        cy.get('#password').type('Redmine@123')
        cy.get('#login-submit').click()
        cy.get(':nth-child(3) > .projects').click()
        cy.get('.issues').click()
        cy.get('.icon-add').click()
        cy.get('#issue_subject').click()
        cy.get('#issue_subject').type('Testing')
        cy.get('#issue_description').click()
        cy.get('#issue_description').type('Automation testing test.')
        cy.get('#issue_status_id').select('new')
        cy.get('#issue_priority_id').select('p1')
        cy.get('.assign-to-me-link').click()
        cy.get('#issue_start_date').click()
        cy.get('#issue_start_date').type('2024-03-02')
        cy.get('#issue_due_date').click()
        cy.get('#issue_due_date').type('2024-03-05')
        cy.get('[name="commit"]').click()       
    })
})